spring.profiles.active=dev

# Dev-specific overrides
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/my_restaurant
spring.datasource.username=root
spring.datasource.password=1234

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
