package com.hellfire.model;

import com.hellfire.config.EncryptedStringConverter;
import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Settlement of a restaurant's earnings for a period. Generated by the team, paid by manual bank
 * transfer to the snapshot of the restaurant's payout account taken at generation time.
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "payouts")
public class Payout {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(optional = false)
    @ToString.Exclude
    private Restaurant restaurant;

    private LocalDate periodStart;
    private LocalDate periodEnd;

    private int paymentCount;

    @Column(precision = 12, scale = 2)
    private BigDecimal grossAmount;

    @Column(precision = 12, scale = 2)
    private BigDecimal refundedAmount;

    /** Platform default at generation time; per-payment snapshots drive the actual commission. */
    @Column(precision = 5, scale = 2)
    private BigDecimal commissionPercentage;

    @Column(precision = 12, scale = 2)
    private BigDecimal commissionAmount;

    @Column(precision = 12, scale = 2)
    private BigDecimal netAmount;

    @Column(length = 3)
    private String currency;

    @Enumerated(EnumType.STRING)
    private PayoutStatus status;

    private LocalDateTime createdAt;
    private String createdBy;
    private LocalDateTime paidAt;
    private String paidBy;
    private String referenceNumber;

    @Column(length = 1000)
    private String notes;

    // ---- destination snapshot
    private String accountHolderName;
    private String bankName;
    private String ifsc;

    @Convert(converter = EncryptedStringConverter.class)
    @Column(length = 512)
    @ToString.Exclude
    private String accountNumber;
}
